sudo: false
language: node_js
node_js:
  - '0.12'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run deploy
env:
  global:
    secure: ZNkSljmI1u9Tr5mnp3nSmCucVDwN48xcMi7H63QnVnpbZXTBDzzjh0n/njj8mR3Bs0THzP0/2hh+swNhesIRlVVPbsrJJ88PJzneFMiRriztI2z07dYr1pHfRktEdkoccU/2p8w8Z+OHJiIMKSnjJEGY6v1s6mtA3/2wXlfJC6Q=
